openapi: 3.0.3
info:
  title: API Documentation
  version: 1.5.7 (1.3)
  description: Source of truth and network automation platform
  license:
    name: Apache v2 License
paths:
  /circuits/circuit-terminations/:
    post:
      operationId: circuits_circuit_terminations_create
      description: |-
        Base class to use for API ViewSets based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support Notes.
      tags:
        - circuits
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WritableCircuitTerminationRequest"
        required: true
      security:
        - cookieAuth: []
        - tokenAuth: []
      responses:
        "201":
          content:
            application/json; version=1.3:
              schema:
                $ref: "#/components/schemas/CircuitTermination"
          description: ""
    put:
      operationId: circuits_circuit_terminations_bulk_update
      description: |-
        Base class to use for API ViewSets based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support Notes.
      tags:
        - circuits
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/BulkWritableCircuitTerminationRequest"
        required: true
      security:
        - cookieAuth: []
        - tokenAuth: []
      responses:
        "200":
          content:
            application/json; version=1.3:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CircuitTermination"
          description: ""
    patch:
      operationId: circuits_circuit_terminations_bulk_partial_update
      description: |-
        Base class to use for API ViewSets based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support Notes.
      tags:
        - circuits
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/PatchedBulkWritableCircuitTerminationRequest"
        required: true
      security:
        - cookieAuth: []
        - tokenAuth: []
      responses:
        "200":
          content:
            application/json; version=1.3:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CircuitTermination"
          description: ""
components:
  schemas:
    CircuitTermination:
      type: object
      description: |-
        Base class to use for serializers based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support custom fields and relationships.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        display:
          type: string
          readOnly: true
          description: Human friendly display value
        url:
          type: string
          format: uri
          readOnly: true
        description:
          type: string
          maxLength: 200
      required:
        - display
        - id
        - url
    WritableCircuitTerminationRequest:
      type: object
      description: |-
        Base class to use for serializers based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support custom fields and relationships.
      properties:
        circuit:
          type: string
          format: uuid
        site:
          type: string
          format: uuid
          nullable: true
        location:
          type: string
          format: uuid
          nullable: true
        provider_network:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          maxLength: 200
        custom_fields:
          type: object
          additionalProperties: {}
        relationships:
          type: object
          additionalProperties:
            type: object
            required:
              - id
              - url
              - name
              - type
            properties:
              id:
                type: string
                format: uuid
                readOnly: true
              url:
                type: string
                format: uri
                readOnly: true
              name:
                type: string
                readOnly: true
              type:
                type: string
                readOnly: true
                example: one-to-many
              source:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
              destination:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
              peer:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
      required:
        - circuit
    BulkWritableCircuitTerminationRequest:
      type: object
      description: |-
        Base class to use for serializers based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support custom fields and relationships.
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
          maxLength: 200
        custom_fields:
          type: object
          additionalProperties: true
        relationships:
          type: object
          additionalProperties:
            type: object
            required:
              - id
              - url
              - name
              - type
            properties:
              id:
                type: string
                format: uuid
                readOnly: true
              url:
                type: string
                format: uri
                readOnly: true
              name:
                type: string
                readOnly: true
              type:
                type: string
                readOnly: true
                example: one-to-many
              source:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
              destination:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
              peer:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
      required:
        - id
    PatchedBulkWritableCircuitTerminationRequest:
      type: object
      description: |-
        Base class to use for serializers based on OrganizationalModel or PrimaryModel.

        Can also be used for models derived from BaseModel, so long as they support custom fields and relationships.
      properties:
        id:
          type: string
          format: uuid
        port_speed:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
          title: Port speed (Kbps)
        upstream_speed:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
          title: Upstream speed (Kbps)
          description: Upstream speed, if different from port speed
        xconnect_id:
          type: string
          title: Cross-connect ID
          maxLength: 50
        pp_info:
          type: string
          title: Patch panel/port(s)
          maxLength: 100
        description:
          type: string
          maxLength: 200
        custom_fields:
          type: object
          additionalProperties: {}
        relationships:
          type: object
          additionalProperties:
            type: object
            required:
              - id
              - url
              - name
              - type
            properties:
              id:
                type: string
                format: uuid
                readOnly: true
              url:
                type: string
                format: uri
                readOnly: true
              name:
                type: string
                readOnly: true
              type:
                type: string
                readOnly: true
                example: one-to-many
              source:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
              destination:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
              peer:
                type: object
                properties:
                  label:
                    type: string
                    readOnly: true
                  object_type:
                    type: string
                    readOnly: true
                    example: dcim.site
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        url:
                          type: string
                          format: uri
                          readOnly: true
                        display:
                          type: string
                          readOnly: true
                      additionalProperties: true
      required:
        - id
